/**
 * Every screen in the product, generated from docs/screen-inventory.md.
 *
 * `node` is the Figma node id — pull the frame with:
 *   get_design_context(fileKey: "H6SDkbXPzmF8l2DkDQmvB9", nodeId: "<node>")
 *
 * Screens without a real component render <Placeholder>. Replacing one means
 * adding a lazy import to SCREEN_COMPONENTS in router.tsx keyed by path.
 */
export type ScreenRoute = { path: string; title: string; node: string }

export const SCREENS: ScreenRoute[] = [
  { path: '/admin', title: 'Executive Dashboard (high fidelity)', node: '7:15548' },
  { path: '/admin/academic', title: 'Academic Management', node: '7:13082' },
  { path: '/admin/admissions', title: 'Admission Management', node: '7:12631' },
  { path: '/admin/admissions/:id', title: 'Application Review Workspace', node: '7:12274' },
  { path: '/admin/exams', title: 'Examination Management Hub', node: '7:17176' },
  { path: '/admin/exams/marks', title: 'Marks Entry & Results Workspace', node: '7:14290' },
  { path: '/admin/exams/schedule', title: 'Exam Scheduling & Timetable Matrix', node: '7:16290' },
  { path: '/admin/finance', title: 'Finance & Accounts Control Center', node: '7:11851' },
  { path: '/admin/users', title: 'User Management', node: '7:17990' },
  { path: '/admin/users/:id', title: 'User Management & Security Profile', node: '7:15889' },
  { path: '/faculty', title: 'Dashboard (3×2 metrics)', node: '1:2' },
  { path: '/faculty/academic', title: 'Academic Overview', node: '1:1147' },
  { path: '/faculty/assignments', title: 'Assignments Overview', node: '1:1841' },
  { path: '/faculty/assignments/:id/review', title: 'Assignments Review', node: '1:4053' },
  { path: '/faculty/attendance', title: 'Attendance Management (final hi-fi)', node: '1:2938' },
  { path: '/faculty/courses', title: 'Courses Management', node: '1:3640' },
  { path: '/faculty/courses/assigned', title: 'My Assigned Courses', node: '1:433' },
  { path: '/faculty/exams', title: 'Examination Management', node: '1:3320' },
  { path: '/faculty/finance', title: 'Personal Finance', node: '1:4777' },
  { path: '/faculty/gradebook', title: 'Grade Book Management', node: '1:2169' },
  { path: '/faculty/library', title: 'Library Resources', node: '1:5381' },
  { path: '/faculty/profile', title: 'Profile (hero layout)', node: '1:868' },
  { path: '/faculty/research', title: 'Research Portfolio', node: '1:5077' },
  { path: '/faculty/research/grants', title: 'Research & Grant Management', node: '1:1490' },
  { path: '/student', title: 'Student Dashboard — Desktop', node: '9:6820' },
  { path: '/student/academic/calendar', title: 'Academic Calendar', node: '6:9314' },
  { path: '/student/academic/classrooms', title: 'Classroom Information', node: '6:8199' },
  { path: '/student/academic/courses', title: 'My Courses', node: '6:11399' },
  { path: '/student/academic/credits', title: 'Credit Progress', node: '6:8940' },
  { path: '/student/academic/curriculum', title: 'Curriculum', node: '6:10057' },
  { path: '/student/academic/degree-progress', title: 'Degree Progress', node: '6:9702' },
  { path: '/student/academic/faculty', title: 'Faculty Directory (2-col grid)', node: '6:7770' },
  { path: '/student/academic/registration/courses', title: 'Course Registration', node: '6:10774' },
  { path: '/student/academic/registration/drop-add', title: 'Drop/Add Course', node: '6:10404' },
  { path: '/student/academic/registration/semester', title: 'Semester Registration', node: '6:11107' },
  { path: '/student/academic/routine', title: 'Class Routine', node: '6:8554' },
  { path: '/student/ai', title: 'AI Assistant Overview', node: '1:5657' },
  { path: '/student/ai/advisor', title: 'AI Academic Advisor', node: '1:7728' },
  { path: '/student/ai/assignment-helper', title: 'AI Assignment Helper', node: '1:7430' },
  { path: '/student/ai/chat', title: 'AI Chat Workspace', node: '1:6099' },
  { path: '/student/ai/notes', title: 'AI Note Generator', node: '1:6831' },
  { path: '/student/ai/quiz', title: 'AI Quiz Generator', node: '1:7161' },
  { path: '/student/ai/recommendations', title: 'AI Course Recommendation', node: '1:8101' },
  { path: '/student/ai/study-planner', title: 'AI Study Planner', node: '1:6424' },
  { path: '/student/attendance', title: 'Attendance Overview (3×2 metrics)', node: '1:15772' },
  { path: '/student/attendance/analytics', title: 'Attendance Analytics', node: '1:14266' },
  { path: '/student/attendance/by-course', title: 'Course Attendance', node: '1:14603' },
  { path: '/student/attendance/daily', title: 'Daily Attendance', node: '1:15435' },
  { path: '/student/attendance/history', title: 'Attendance History', node: '1:15013' },
  { path: '/student/certificates', title: 'Certificates', node: '6:5438' },
  { path: '/student/exams', title: 'Examination Overview', node: '1:8461' },
  { path: '/student/exams/admit-card', title: 'Admit Card', node: '1:10550' },
  { path: '/student/exams/analytics', title: 'Exam Analytics', node: '1:13501' },
  { path: '/student/exams/attendance', title: 'Exam Attendance Sheet', node: '1:13906' },
  { path: '/student/exams/grade-report', title: 'Grade Report', node: '1:11742' },
  { path: '/student/exams/results', title: 'Exam Results', node: '1:12105' },
  { path: '/student/exams/revaluation', title: 'Exam Revaluation', node: '1:13158' },
  { path: '/student/exams/schedule', title: 'My Exam Schedule', node: '1:9040' },
  { path: '/student/exams/upcoming', title: 'Upcoming Exams', node: '1:10924' },
  { path: '/student/finance', title: 'Finance Overview', node: '1:9705' },
  { path: '/student/finance/history', title: 'Payment History', node: '1:11319' },
  { path: '/student/finance/installments', title: 'Installment Plan', node: '1:12857' },
  { path: '/student/finance/invoices', title: 'Invoices', node: '1:12541' },
  { path: '/student/finance/pay', title: 'Make Payment', node: '1:9415' },
  { path: '/student/finance/statement', title: 'Fee Statement', node: '1:10138' },
  { path: '/student/lms', title: 'LMS Overview', node: '6:2' },
  { path: '/student/lms/analytics', title: 'Learning Analytics', node: '6:6146' },
  { path: '/student/lms/announcements', title: 'Course Announcements', node: '6:6849' },
  { path: '/student/lms/assignments', title: 'Assignments', node: '6:2928' },
  { path: '/student/lms/assignments/:id/submit', title: 'Assignment Submission', node: '6:3292' },
  { path: '/student/lms/courses', title: 'My Courses', node: '6:439' },
  { path: '/student/lms/courses/:id/lectures', title: 'Video Lectures', node: '6:1451' },
  { path: '/student/lms/courses/:id/materials', title: 'Course Materials', node: '6:2191' },
  { path: '/student/lms/downloads', title: 'Downloads', node: '6:5838' },
  { path: '/student/lms/forum', title: 'Discussion Forum', node: '6:3933' },
  { path: '/student/lms/gradebook', title: 'Gradebook', node: '6:7427' },
  { path: '/student/lms/live', title: 'Live Classes', node: '6:1780' },
  { path: '/student/lms/notes', title: 'Notes', node: '6:4677' },
  { path: '/student/lms/progress', title: 'Learning Progress', node: '6:5065' },
  { path: '/student/lms/quizzes', title: 'Quizzes', node: '6:3564' },
  { path: '/student/lms/quizzes/:id/practice', title: 'Practice Quiz', node: '6:4278' },
  { path: '/student/lms/recordings', title: 'Recorded Classes', node: '6:2573' },
  { path: '/student/profile', title: 'My Profile Dashboard', node: '11:4256' },
  { path: '/student/profile/academic', title: 'Academic Information', node: '11:4476' },
  { path: '/student/profile/documents', title: 'Documents Manager', node: '11:3993' },
  { path: '/student/profile/activity', title: 'Activity Log', node: '11:4782' },
  { path: '/student/profile/security', title: 'Security Panel', node: '11:5223' },
]
